analyzer:
  exclude:
    - lib/generated/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/generated_plugin_registrant.dart
    - test/**/*.mocks.dart
  errors:
    invalid_annotation_target: ignore

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    require_trailing_commas: true
    always_use_package_imports: true
    avoid_empty_else: true
    avoid_print: true
    avoid_types_as_parameter_names: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    eol_at_end_of_file: true
    omit_local_variable_types: true
